-- MySQL Script generated by MySQL Workbench
-- Sat Oct 12 21:58:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PalaceDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PalaceDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PalaceDatabase` DEFAULT CHARACTER SET utf8 ;
USE `PalaceDatabase` ;

-- -----------------------------------------------------
-- Table `PalaceDatabase`.`ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PalaceDatabase`.`ITEM` ;

CREATE TABLE IF NOT EXISTS `PalaceDatabase`.`ITEM` (
  `SKU` INT NOT NULL,
  `Picture` BLOB NULL,
  `Price` DECIMAL(10,2) NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Quantity` INT NOT NULL,
  `Sold_Date` DATETIME NULL,
  PRIMARY KEY (`SKU`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PalaceDatabase`.`ITEM_TAGS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PalaceDatabase`.`ITEM_TAGS` ;

CREATE TABLE IF NOT EXISTS `PalaceDatabase`.`ITEM_TAGS` (
  `SKU` INT NOT NULL,
  `Tag` VARCHAR(45) NULL,
  PRIMARY KEY (`SKU`),
  CONSTRAINT `fk_ITEM_TAGS_ITEM`
    FOREIGN KEY (`SKU`)
    REFERENCES `PalaceDatabase`.`ITEM` (`SKU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PalaceDatabase`.`EMPLOYEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PalaceDatabase`.`EMPLOYEE` ;

CREATE TABLE IF NOT EXISTS `PalaceDatabase`.`EMPLOYEE` (
  `Employee_ID` INT NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Position` VARCHAR(45) NULL,
  `EmployeeEmail` VARCHAR(80) NOT NULL,
  `EmployeePhone` VARCHAR(20) NULL,
  PRIMARY KEY (`Employee_ID`),
  UNIQUE INDEX `Employee_ID_UNIQUE` (`Employee_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PalaceDatabase`.`CUSTOMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PalaceDatabase`.`CUSTOMER` ;

CREATE TABLE IF NOT EXISTS `PalaceDatabase`.`CUSTOMER` (
  `Customer_ID` INT NOT NULL,
  `First_Name` VARCHAR(50) NULL,
  `Last_Name` VARCHAR(50) NOT NULL,
  `Customer_Phone` VARCHAR(20) NULL,
  `Customer_Email` VARCHAR(45) NULL,
  `Customercol` VARCHAR(45) NULL,
  PRIMARY KEY (`Customer_ID`),
  UNIQUE INDEX `Customer_ID_UNIQUE` (`Customer_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PalaceDatabase`.`ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PalaceDatabase`.`ORDER` ;

CREATE TABLE IF NOT EXISTS `PalaceDatabase`.`ORDER` (
  `Order_Number` INT NOT NULL,
  `Customer_ID` INT NOT NULL,
  `Employee_ID` INT NOT NULL,
  `Subtotal` DECIMAL(10,2) NOT NULL,
  `Tax` DECIMAL(10,2) NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Order_Number`),
  INDEX `fk_ORDER_EMPLOYEE1_idx` (`Employee_ID` ASC) VISIBLE,
  INDEX `fk_ORDER_CUSTOMER1_idx` (`Customer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ORDER_EMPLOYEE1`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `PalaceDatabase`.`EMPLOYEE` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_CUSTOMER1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `PalaceDatabase`.`CUSTOMER` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PalaceDatabase`.`ORDER_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PalaceDatabase`.`ORDER_ITEM` ;

CREATE TABLE IF NOT EXISTS `PalaceDatabase`.`ORDER_ITEM` (
  `Order_Number` INT NOT NULL,
  `SKU` INT NULL,
  PRIMARY KEY (`Order_Number`),
  INDEX `fk_ORDER_ITEM_ITEM1_idx` (`SKU` ASC) VISIBLE,
  CONSTRAINT `fk_ORDER_ITEM_ITEM1`
    FOREIGN KEY (`SKU`)
    REFERENCES `PalaceDatabase`.`ITEM` (`SKU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_ITEM_ORDER1`
    FOREIGN KEY (`Order_Number`)
    REFERENCES `PalaceDatabase`.`ORDER` (`Order_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PalaceDatabase`.`REPAIR_ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PalaceDatabase`.`REPAIR_ORDER` ;

CREATE TABLE IF NOT EXISTS `PalaceDatabase`.`REPAIR_ORDER` (
  `Repair_Order_Number` INT NOT NULL,
  `Employee_ID` INT NOT NULL,
  `Customer_ID` INT NOT NULL,
  `Subtotal` DECIMAL(10,2) NOT NULL,
  `Tax` DECIMAL(10,2) NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  `ITEM_TAGS_SKU` INT NOT NULL,
  PRIMARY KEY (`Repair_Order_Number`),
  INDEX `fk_REPAIR_ORDER_CUSTOMER1_idx` (`Customer_ID` ASC) VISIBLE,
  INDEX `fk_REPAIR_ORDER_EMPLOYEE1_idx` (`Employee_ID` ASC) VISIBLE,
  CONSTRAINT `fk_REPAIR_ORDER_CUSTOMER1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `PalaceDatabase`.`CUSTOMER` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REPAIR_ORDER_EMPLOYEE1`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `PalaceDatabase`.`EMPLOYEE` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PalaceDatabase`.`REPAIR_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PalaceDatabase`.`REPAIR_ITEM` ;

CREATE TABLE IF NOT EXISTS `PalaceDatabase`.`REPAIR_ITEM` (
  `Repair_Order_Number` INT NOT NULL AUTO_INCREMENT,
  `Customer_ID` INT NOT NULL,
  `Picture` BLOB NULL,
  `Descriptin` VARCHAR(255) NULL,
  `Name` VARCHAR(80) NULL,
  `Repair_Item_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Repair_Item_ID`),
  INDEX `fk_REPAIR_ITEM_REPAIR_ORDER1_idx` (`Repair_Order_Number` ASC) VISIBLE,
  CONSTRAINT `fk_REPAIR_ITEM_REPAIR_ORDER1`
    FOREIGN KEY (`Repair_Order_Number`)
    REFERENCES `PalaceDatabase`.`REPAIR_ORDER` (`Repair_Order_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PalaceDatabase`.`EMPLOYEE_LOGIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PalaceDatabase`.`EMPLOYEE_LOGIN` ;

CREATE TABLE IF NOT EXISTS `PalaceDatabase`.`EMPLOYEE_LOGIN` (
  `Employee_ID` INT NOT NULL,
  `Employee_Username` VARCHAR(45) NOT NULL,
  `Employee_Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Employee_ID`),
  CONSTRAINT `fk_EMPLOYEE_LOGIN_EMPLOYEE1`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `PalaceDatabase`.`EMPLOYEE` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
